# Generated by Django 3.0.1 on 2019-12-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='create_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='service',
            name='seo_desc',
            field=models.CharField(default='', max_length=250, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='seo_keywords',
            field=models.CharField(default='', max_length=250, verbose_name='Keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=250, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
