# Generated by Django 3.0.1 on 2019-12-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('services', '0005_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(related_name='services', to='doctors.Doctor', verbose_name='Доктора'),
        ),
    ]
