# Generated by Django 3.0.1 on 2019-12-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='doctors',
        ),
    ]
