# Generated by Django 3.0.1 on 2019-12-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='seo_desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='seo_desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords'),
        ),
    ]
