# Generated by Django 3.0.1 on 2019-12-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='Akusher', max_length=250, verbose_name='Специальность'),
            preserve_default=False,
        ),
    ]
